.github/workflows/build-backend.yml
.github/workflows/build-frontend.yml
.github/workflows/composites/kosli-attest-dir-artifact/action.yml
.github/workflows/composites/kosli-attest-jira/action.yml
.github/workflows/composites/kosli-attest-pullrequest/action.yml
.github/workflows/composites/kosli-begin-trail/action.yml
.github/workflows/secret-expire-check.yml
apps/backend/backend-content.txt
apps/backend/kosli-template.yml
apps/frontend/kosli-template.yml
secrets/gh-repo-kosli-jira-api-token.txt
secrets/gh-repo-kosli-jira-username.txt
secrets/gh-repo-kosli-public-api-token.txt

- **Added build actions**
- **OPS-3 updated backend source**

Added actions

---

Makefile
apps/backend/backend-content.txt
apps/frontend/frontend-content.txt

- **Added missing timestamp in makefile**
- **OPS-3 extra whitespace**

add missing timestamp

---

.github/workflows/simulate-environment-reporting-prod.yml
apps/backend/backend-content.txt
apps/frontend/frontend-content.txt

- **OPS-3 Added prod reporting**
- **OPS-3 updated apps**

prod env reporting

---

.github/workflows/deploy-to-staging.yml

- **Fetch more from git when doing deploy to staging**
- **OPS-3 Fetch more from git when doing deploy to staging**
- **OPS-3 removed debugging**

fix deploy to staging 2

---

.github/workflows/create-release.yml
apps/backend/backend-content.txt
apps/frontend/frontend-content.txt
scripts/lib-jira.sh
scripts/lib-kosli.sh

- **OPS-8 Cleaned up things in lib-jira**
- **OPS-8 Added some debugging**
- **OPS-8 added more debug**
- **OPS-8 do less in job**
- **Fixed wrong URL**
- **Revert back to actual create release**
- **Adding JIRA tickets to release**
- **some debug**
- **some debug**
- **some debug**
- **Added missing kosli command**
- **added some debug**
- **More testing**
- **more debug**
- **Only get existing JIRA keys**
- **Revert back commented out code**
- **OPS-8 Updated apps**

OPS-8 Added job to create a release candidate

---

.github/workflows/deploy-to-staging.yml
scripts/lib-kosli.sh

- **OPS-12 Update of get curren running env json**
- **OPS-12 Added debugging**
- **OPS-12 Changed variable assingment**
- **OPS-12 Store current env json in file**

OPS 12 deploy dev to staging 3

---

.github/workflows/deploy-to-staging.yml

- **OPS-12 Added content permission for github action**
- **OPS-12 Fixed indentation**
- **OPS-12 Added workflows permissions**
- **OPS-12 added id-token permission**
- **OPS-12 Try write-all permission**
- **OPS-12 Try export github token**
- **OPS-12 Try export github token with GH**
- **OPS-12 Added debugging**
- **OPS-12 more debug**
- **OPS-12 more debug**
- **OPS-12 New secret**
- **OPS-12 more debug**
- **OPS-12 more debug**
- **OPS-12 more debug**
- **OPS-12 more debug**
- **OPS-12 more debug**
- **OPS-12 try GITHUB api**
- **OPS-12 update secret**
- **OPS-12 update commit sha**
- **OPS-12 added backend**
- **OPS-12 Removed permission setting**
- **OPS-12 Removed debug**

OPS-12 Fixed deploy to staging script

---

.github/workflows/update-release.yml
scripts/lib-jira.sh
scripts/lib-kosli.sh

- **OPS-13 added debug**
- **OPS-13 Update rel candicate with OPS-8**

OPS-13 Added support for update of release

---

.github/workflows/create-release.yml
.github/workflows/update-release.yml
Makefile

- **OPS-13 Fixed variable flow source**
- **OPS-13 fixed missing parantese**

OPS-13 Fixed update release

---

.github/workflows/release-to-prod.yml
Makefile

- **OPS-14 Fixed typo**
- **OPS-14 Echo to stderr**
- **OPS-14 sleep after last echo to get it in log**
- **OPS-14 send debug info to github step summary**
- **OPS-14 more debug**
- **OPS-14 added missing jira envs**
- **OPS-14 fixed typo**
- **OPS-14 removed debug**

OPS-14 Fixed release to prod script

---

.github/workflows/release-to-prod.yml
scripts/lib-jira.sh

- **OPS-14 Added setting release to released in jira**
- **OPS-14 moved envs**
- **OPS-14 fixed typo**
- **OPS-14 fixed typo**

OPS-14 update jira ticket after deploy to prod

---

.github/workflows/create-release.yml
.github/workflows/update-release.yml

- **OPS-15 fixed typo**
- **OPS-15 Update release report to kosli**

OPS-15 Fixed jira reporting in release

---

.github/workflows/create-release.yml
.github/workflows/update-release.yml

- **OPS-15 Added missing flow name in update-release**
- **OPS-15 added debugging**
- **OPS-15 fixed jira issue loop**
- **OPS-15 fixed typo**
- **OPS-15 Removed debugging**
- **OPS-15 Cleanup**

OPS-15 Fixed update realease script

---

.github/workflows/release-to-prod.yml
apps/backend/backend-content.txt
apps/frontend/frontend-content.txt

- **OPS-15 Fixed attest approval**
- **OPS-15 SW version 16**

OPS-15 SW version 16

---

.github/workflows/create-release.yml
.github/workflows/update-release.yml
scripts/lib-jira.sh
scripts/lib-kosli.sh

- **OPS-19 Cleaned up lib shell scripts**
- **OPS-19 Added debug print**

OPS 19 cleanup up functions and add debug option

---

.github/workflows/release-to-prod.yml
README.md

- **Added more to readme**
- **OPS-24 Added README**

OPS-24 Added README

---

.github/workflows/setup-kosli.yml

- **OPS-26 Update create policy command**
- **OPS-26 Attach policies**

OPS-26 Attached policies to environments

---

apps/backend/backend-content.txt
apps/frontend/frontend-content.txt

- **Update apps to 30**
- **OPS-26 Update apps to 30**

OPS-26 update apps to version 30

---

.github/workflows/release-to-prod.yml

- **OPS-26 fixed typo in reporting**
- **OPS-26 only do deploy after attest approval**

OPS-26 fix release

---

.github/workflows/release-to-prod.yml
apps/backend/backend-content.txt
apps/frontend/frontend-content.txt
scripts/lib-jira.sh
scripts/relese-what-i-have-now.sh

- **OPS-27 Fixed typo in release to prod scripts**
- **Fixed getting user details**
- **OPS-27 apps version 34**

OPS-27 Fixed bugs in getting name of approver

---

.github/workflows/attest-source-controls.yml
.github/workflows/build-backend.yml
.github/workflows/build-frontend.yml
.github/workflows/create-release.yml
.github/workflows/deploy-to-staging.yml
.github/workflows/release-to-prod.yml
.github/workflows/setup-kosli.yml
.github/workflows/simulate-environment-reporting-dev.yml
.github/workflows/simulate-environment-reporting-prod.yml
.github/workflows/simulate-environment-reporting-staging.yml
.github/workflows/update-release.yml

- **OPS-28 convert from vars to env in actions**
- **OPS-28 More vars to env conversions**

OPS-28 More vars to env conversions

---

.github/workflows/release-to-prod.yml
.github/workflows/setup-kosli.yml
approval-jira-schema.json

- **OPS-30 Added attestation-jira custom type**
- **OPS-30 Use attestation-jira**

OPS-30 Added attestation-jira custom type

---

README.md
kosli-prod-policy.yml

- **OPS-30 Require that release-approval is of type approval-jira**
- **OPS-30 Updated readme**

OPS-30 Require that release-approval is of type approval-jira

---

.github/workflows/release-to-prod.yml
.github/workflows/setup-kosli.yml
README.md
apps/frontend/frontend-content.txt
kosli-release-template.yml

- **OPS-32 Added template to release flow. Frontend version 37**
- **OPS-32 Changed name of release to prod**

OPS-32 Added template to release flow. Frontend version 37

---

.github/workflows/create-release.yml
.github/workflows/release-to-prod.yml
kosli-flow-templates/release-template.yml

- **OPS-37 Added current running prod SW to the release**
- **OPS-37 Only run check for release to prod on demand**

OPS-37 Added current running prod SW to the release

---

.github/actions/kosli-attest-jira/action.yml
.github/workflows/attest-source-controls.yml
.github/workflows/build-backend.yml
.github/workflows/build-frontend.yml
apps/backend/backend-content.txt

- **Commit with missing key**
- **OPS-39 Commit with key**
- **OPS-39 Added using project key in actions**
- **TMH-39 Test with wrong key**
- **TMH-55 Added debug**
- **TMH-55 Added debug of version**
- **OPS-39 Debug with correct key**
- **OPS-39 Removed debug info**

OPS 39 use jira project key

---

.github/workflows/build-backend.yml
.github/workflows/build-frontend.yml
apps/backend/backend-content.txt
apps/frontend/frontend-content.txt

- **ops-41 Test with lower case and new kosli version**
- **Allow Jira issue lower case in build workflows**

Allow lower case Jira issue in build workflows

---

.github/workflows/get-project-id.yml
scripts/lib-kosli.sh

- **Use new kosli command and not curl to get attestation**
- **Added debugging**
- **Fixed wrong file name**
- **Added output**
- **Debug**
- **Debug**
- **Add missing secrets**

OPS-44 Use Kosli CLI and not curl to get attestation

---

.github/workflows/release-to-prod.yml
apps/backend/backend-content.txt
apps/frontend/frontend-content.txt

- **Test link generation**
- **OPS-45 Added link from approval back to jira ticket**

OPS-45 Added link from approval back to jira release

---

.github/workflows/update-release.yml

- **OPS-49 Fixed update-release**
- **OPS-49 Remove debug**

OPS 49 fix update

---

apps/backend/backend-content.txt
apps/frontend/frontend-content.txt

OPS 57 more greater

---

.github/actions/generate-jira-release/action.yml
.github/workflows/generate-jira-release.yml
scripts/lib-jira.sh

- **OPS-64 started on moving generate-jira-relase into an action**
- **Debug**
- **Debug**
- **Debug**
- **OPS-64 Removed debug**
- **OPS-64 Some cleanup**

OPS-64 Moved generate-jira-release into a composite action

---

.github/workflows/setup-kosli.yml

- **Added some white space**
- **Removed some other white space**

OPS 69 other branch
